### ISSUE TITLE
adding new key in \tagstructbegin command

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [u-fischer/tagpdf#22]
In mc i have raw key,in which i can use law-level commands of pdf format. can you please add the same key for struct to? Thanks.

**Comment by u-fischer** [comment]
For which use case? Which dictionary entry do you want to add with it?

**Comment by bdoubrov** [comment]
According to the documentation of tagpdf 0.6.1, it is possible to use `raw` key-value in the `\tagmcbegin` command:

**Comment by u-fischer** [comment]
@bdoubrov yes it could be added. But why do you need it? Which specific entry in \tagstructbegin are you missing? I want to know if `raw` is really the best solution, or if some more specific key is needed.

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer because in this case we can,for example,add params,which need for associative files or any other params,which can be appeared in new versions of pdf standard. For mc we can do it,using raw key,so it would be very good,if this feature will be for structure to.

**Comment by bdoubrov** [comment]
Comparing the list of available entries in the \tagstructbegin with the ones in the Structure element dictionary in PDF 2.0, I see at least the following missing entries:
- Ref - very useful if one structure element references another (A Ref identifies the structure element or elements to which the item of content, contained within this structure element, refers (e.g. footnotes, endnotes, sidebars, etc.).
- Lang - a language identifier. Essential if the structure element contains some text in a different language. For example, a <span> tag with surrounding English phrase in otherwise German text
- E - The expanded form of an abbreviation or an acronym such as Dr., Prof. Emer., and others

**Comment by u-fischer** [comment]
I added support for Ref, Lang and E in the new version 0.8 that I just uploaded. This version requires the new pdf management of LaTeX which is in the pdfmanagement-testphase package that I uploaded too.
