### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by glasgowm148** [u-fischer/tagpdf#51]
Appreciate your work here but could add some instructions for use?

I'm using Overleaf to edit currently - how do I go from that to a tagged PDF? (Still surprised picking up `section and `subsection` isn't the default as a bare minimum)

**Comment by u-fischer** [comment]
The documentation starts with "This package is not meant for normal document production. It is mainly a tool to research tagging. You need a very current LATEX format."  

This is meant in earnest. There are no user level instructions, and the latex on overleaf is probably to old. If you want to use it, you will have to study the documentation and the examples and do some research.

 > Still surprised picking up section and subsection isn't the default as a bare minimum

Patching section and subsection in a specific class so that they are tagged is quite trivial. The documentation does it. But it is not the aim of the package to do such patches. Instead we want to change LaTeX, and that is not trivial at all as we have to be careful not to break existing documents.
